export const Andhra_Pradesh = [
  { name: "Adoni", slug: "adoni" },
  { name: "Amalapuram", slug: "amalapuram" },
  { name: "Anakapalle", slug: "anakapalle" },
  { name: "Anantapur", slug: "anantapur" },
  { name: "Bapatla", slug: "bapatla" },
  { name: "Chilakaluripet", slug: "chilakaluripet" },
  { name: "Chirala", slug: "chirala" },
  { name: "Chittoor", slug: "chittoor" },
  { name: "Dharmavaram", slug: "dharmavaram" },
  { name: "Eluru", slug: "eluru" },
  { name: "Gudivada", slug: "gudivada" },
  { name: "Guntakal", slug: "guntakal" },
  { name: "Guntur", slug: "guntur" },
  { name: "Hindupur", slug: "hindupur" },
  { name: "Kadapa", slug: "kadapa" },
  { name: "Kakinada", slug: "kakinada" },
  { name: "Kurnool", slug: "kurnool" },
  { name: "Machilipatnam", slug: "machilipatnam" },
  { name: "Madanapalle", slug: "madanapalle" },
  { name: "Nandyal", slug: "nandyal" },
  { name: "Narasaraopet", slug: "narasaraopet" },
  { name: "Nellore", slug: "nellore" },
  { name: "Ongole", slug: "ongole" },
  { name: "Palakollu", slug: "palakollu" },
  { name: "Palasa", slug: "palasa" },
  { name: "Pamur", slug: "pamur" },
  { name: "Pattikonda", slug: "pattikonda" },
  { name: "Payakaraopet", slug: "payakaraopet" },
  { name: "Peddapuram", slug: "peddapuram" },
  { name: "Puttur", slug: "puttur" },
  { name: "Rajahmundry", slug: "rajahmundry" },
  { name: "Rajam", slug: "rajam" },
  { name: "Ramachandrapuram", slug: "ramachandrapuram" },
  { name: "Rayachoti", slug: "rayachoti" },
  { name: "Rayadurg", slug: "rayadurg" },
  { name: "Srikakulam", slug: "srikakulam" },
  { name: "Tenali", slug: "tenali" },
  { name: "Tirupati", slug: "tirupati" },
  { name: "Tuni", slug: "tuni" },
  { name: "Vizianagaram", slug: "vizianagaram" },
  { name: "Wanaparthy", slug: "wanaparthy" },
  { name: "Warangal", slug: "warangal" },
  { name: "Yanam", slug: "yanam" },
];

export const Arunachal_Pradesh = [
  { name: "Along" },
  { name: "Bhalukpong" },
  { name: "Daporijo" },
  { name: "Itanagar" },
  { name: "Jairampur" },
  { name: "Khonsa" },
  { name: "Pasighat" },
  { name: "Roing" },
  { name: "Seppa" },
  { name: "Tezu" },
  { name: "Tawang" },
  { name: "Ziro" },
];

export const Assam = [
  { name: "Barpeta", slug: "barpeta" },
  { name: "Bongaigaon", slug: "bongaigaon" },
  { name: "Dhubri", slug: "dhubri" },
  { name: "Dibrugarh", slug: "dibrugarh" },
  { name: "Diphu", slug: "diphu" },
  { name: "Goalpara", slug: "goalpara" },
  { name: "Golaghat", slug: "golaghat" },
  { name: "Guwahati", slug: "guwahati" },
  { name: "Jorhat", slug: "jorhat" },
  { name: "Karimganj", slug: "karimganj" },
  { name: "Lanka", slug: "lanka" },
  { name: "Lumding", slug: "lumding" },
  { name: "Mangaldoi", slug: "mangaldoi" },
  { name: "Mankachar", slug: "mankachar" },
  { name: "Margherita", slug: "margherita" },
  { name: "Mariani", slug: "mariani" },
  { name: "Marigaon", slug: "marigaon" },
  { name: "Nagaon", slug: "nagaon" },
  { name: "Nalbari", slug: "nalbari" },
  { name: "North Lakhimpur", slug: "north-lakhimpur" },
  { name: "Rangia", slug: "rangia" },
  { name: "Sibsagar", slug: "sibsagar" },
  { name: "Silapathar", slug: "silapathar" },
  { name: "Silchar", slug: "silchar" },
  { name: "Tezpur", slug: "tezpur" },
  { name: "Tinsukia", slug: "tinsukia" },
  { name: "Udalguri", slug: "udalguri" },
  { name: "Ziro", slug: "ziro" },
];

export const Bihar = [
  { name: "Araria", slug: "araria" },
  { name: "Arrah", slug: "arrah" },
  { name: "Aurangabad", slug: "aurangabad" },
  { name: "Bagaha", slug: "bagaha" },
  { name: "Banka", slug: "banka" },
  { name: "Begusarai", slug: "begusarai" },
  { name: "Bettiah", slug: "bettiah" },
  { name: "Bhabua", slug: "bhabua" },
  { name: "Bhagalpur", slug: "bhagalpur" },
  { name: "Bihar Sharif", slug: "bihar-sharif" },
  { name: "Buxar", slug: "buxar" },
  { name: "Chhapra", slug: "chhapra" },
  { name: "Darbhanga", slug: "darbhanga" },
  { name: "Dehri-on-Sone", slug: "dehri-on-sone" },
  { name: "Dinapur Nizamat", slug: "dinapur-nizamat" },
  { name: "Gaya", slug: "gaya" },
  { name: "Gopalganj", slug: "gopalganj" },
  { name: "Hajipur", slug: "hajipur" },
  { name: "Jamalpur", slug: "jamalpur" },
  { name: "Katihar", slug: "katihar" },
  { name: "Madhubani", slug: "madhubani" },
  { name: "Motihari", slug: "motihari" },
  { name: "Munger", slug: "munger" },
  { name: "Muzaffarpur", slug: "muzaffarpur" },
  { name: "Patna", slug: "patna" },
  { name: "Purnia", slug: "purnia" },
  { name: "Pusa", slug: "pusa" },
  { name: "Saharsa", slug: "saharsa" },
  { name: "Samastipur", slug: "samastipur" },
  { name: "Sasaram", slug: "sasaram" },
  { name: "Sitamarhi", slug: "sitamarhi" },
  { name: "Siwan", slug: "siwan" },
  { name: "Supaul", slug: "supaul" },
  { name: "Vaishali", slug: "vaishali" },
];

export const Chhattisgarh = [
  { name: "Ambikapur", slug: "ambikapur" },
  { name: "Baikunthpur", slug: "baikunthpur" },
  { name: "Balod", slug: "balod" },
  { name: "Baloda Bazar", slug: "baloda-bazar" },
  { name: "Balrampur", slug: "balrampur" },
  { name: "Bemetara", slug: "bemetara" },
  { name: "Bhatapara", slug: "bhatapara" },
  { name: "Bijapur", slug: "bijapur" },
  { name: "Bilaspur", slug: "bilaspur" },
  { name: "Champa", slug: "champa" },
  { name: "Dantewada", slug: "dantewada" },
  { name: "Dhamtari", slug: "dhamtari" },
  { name: "Durg", slug: "durg" },
  { name: "Jagdalpur", slug: "jagdalpur" },
  { name: "Janjgir Champa", slug: "janjgir-champa" },
  { name: "Kanker", slug: "kanker" },
  { name: "Kavardha", slug: "kavardha" },
  { name: "Kondagaon", slug: "kondagaon" },
  { name: "Korba", slug: "korba" },
  { name: "Mahasamund", slug: "mahasamund" },
  { name: "Mungeli", slug: "mungeli" },
  { name: "Narayanpur", slug: "narayanpur" },
  { name: "Pandaria", slug: "pandaria" },
  { name: "Raigarh", slug: "raigarh" },
  { name: "Raipur", slug: "raipur" },
  { name: "Rajnandgaon", slug: "rajnandgaon" },
  { name: "Sakti", slug: "sakti" },
  { name: "Surguja", slug: "surguja" },
];

export const Goa = [
  { name: "North Goa", slug: "north-goa" },
  { name: "South Goa", slug: "south-goa" },
];

export const Gujarat = [
  { name: "Ahmedabad", slug: "ahmedabad" },
  { name: "Amreli", slug: "amreli" },
  { name: "Anand", slug: "anand" },
  { name: "Ankleshwar", slug: "ankleshwar" },
  { name: "Banaskantha", slug: "banaskantha" },
  { name: "Bharuch", slug: "bharuch" },
  { name: "Bhavnagar", slug: "bhavnagar" },
  { name: "Bhuj", slug: "bhuj" },
  { name: "Botad", slug: "botad" },
  { name: "Chhota Udepur", slug: "chhota-udepur" },
  { name: "Dahod", slug: "dahod" },
  { name: "Deesa", slug: "deesa" },
  { name: "Dharampur", slug: "dharampur" },
  { name: "Dhoraji", slug: "dhoraji" },
  { name: "Dhrangadhra", slug: "dhrangadhra" },
  { name: "Godhra", slug: "godhra" },
  { name: "Gondal", slug: "gondal" },
  { name: "Himatnagar", slug: "himatnagar" },
  { name: "Idar", slug: "idar" },
  { name: "Jamnagar", slug: "jamnagar" },
  { name: "Junagadh", slug: "junagadh" },
  { name: "Kadi", slug: "kadi" },
  { name: "Kalavad", slug: "kalavad" },
  { name: "Kalol", slug: "kalol" },
  { name: "Kapadvanj", slug: "kapadvanj" },
  { name: "Karjan", slug: "karjan" },
  { name: "Keshod", slug: "keshod" },
  { name: "Khambhalia", slug: "khambhalia" },
  { name: "Khambhat", slug: "khambhat" },
  { name: "Khedbrahma", slug: "khedbrahma" },
  { name: "Kheralu", slug: "kheralu" },
  { name: "Kodinar", slug: "kodinar" },
  { name: "Lathi", slug: "lathi" },
  { name: "Limbdi", slug: "limbdi" },
  { name: "Lunawada", slug: "lunawada" },
  { name: "Mahesana", slug: "mahesana" },
  { name: "Mahuva", slug: "mahuva" },
  { name: "Manavadar", slug: "manavadar" },
  { name: "Mandvi", slug: "mandvi" },
  { name: "Mangrol", slug: "mangrol" },
  { name: "Mansa", slug: "mansa" },
  { name: "Mehmedabad", slug: "mehmedabad" },
  { name: "Modasa", slug: "modasa" },
  { name: "Morvi", slug: "morvi" },
  { name: "Nadiad", slug: "nadiad" },
  { name: "Navsari", slug: "navsari" },
  { name: "Padra", slug: "padra" },
  { name: "Palanpur", slug: "palanpur" },
  { name: "Palitana", slug: "palitana" },
  { name: "Pardi", slug: "pardi" },
  { name: "Patan", slug: "patan" },
  { name: "Petlad", slug: "petlad" },
  { name: "Porbandar", slug: "porbandar" },
  { name: "Radhanpur", slug: "radhanpur" },
  { name: "Rajkot", slug: "rajkot" },
  { name: "Rajpipla", slug: "rajpipla" },
  { name: "Rajula", slug: "rajula" },
  { name: "Ranavav", slug: "ranavav" },
  { name: "Rapar", slug: "rapar" },
  { name: "Salaya", slug: "salaya" },
  { name: "Sanand", slug: "sanand" },
  { name: "Savarkundla", slug: "savarkundla" },
  { name: "Sidhpur", slug: "sidhpur" },
  { name: "Sihor", slug: "sihor" },
  { name: "Songadh", slug: "songadh" },
  { name: "Surat", slug: "surat" },
  { name: "Surendranagar", slug: "surendranagar" },
  { name: "Talaja", slug: "talaja" },
  { name: "Thangadh", slug: "thangadh" },
  { name: "Tharad", slug: "tharad" },
  { name: "Umbergaon", slug: "umbergaon" },
  { name: "Umreth", slug: "umreth" },
  { name: "Una", slug: "una" },
  { name: "Unjha", slug: "unjha" },
  { name: "Upleta", slug: "upleta" },
  { name: "Vadnagar", slug: "vadnagar" },
  { name: "Vadodara", slug: "vadodara" },
  { name: "Valsad", slug: "valsad" },
  { name: "Vapi", slug: "vapi" },
  { name: "Vapi", slug: "vapi" },
  { name: "Veraval", slug: "veraval" },
  { name: "Vijapur", slug: "vijapur" },
  { name: "Viramgam", slug: "viramgam" },
  { name: "Visnagar", slug: "visnagar" },
  { name: "Vyara", slug: "vyara" },
  { name: "Wadhwan", slug: "wadhwan" },
  { name: "Wankaner", slug: "wankaner" },
];

export const Haryana = [
  { name: "Ambala", slug: "ambala" },
  { name: "Bhiwani", slug: "bhiwani" },
  { name: "Charkhi Dadri", slug: "charkhi-dadri" },
  { name: "Faridabad", slug: "faridabad" },
  { name: "Fatehabad", slug: "fatehabad" },
  { name: "Gurgaon", slug: "gurgaon" },
  { name: "Hansi", slug: "hansi" },
  { name: "Hisar", slug: "hisar" },
  { name: "Jind", slug: "jind" },
  { name: "Kaithal", slug: "kaithal" },
  { name: "Karnal", slug: "karnal" },
  { name: "Ladwa", slug: "ladwa" },
  { name: "Mahendragarh", slug: "mahendragarh" },
  { name: "Narnaul", slug: "narnaul" },
  { name: "Narwana", slug: "narwana" },
  { name: "Palwal", slug: "palwal" },
  { name: "Panchkula", slug: "panchkula" },
  { name: "Panipat", slug: "panipat" },
  { name: "Rewari", slug: "rewari" },
  { name: "Rohtak", slug: "rohtak" },
  { name: "Sirsa", slug: "sirsa" },
  { name: "Sonipat", slug: "sonipat" },
  { name: "Yamuna Nagar", slug: "yamuna-nagar" },
];

export const Himachal_Pradesh = [
  { name: "Baddi", slug: "baddi" },
  { name: "Bilaspur", slug: "bilaspur" },
  { name: "Chamba", slug: "chamba" },
  { name: "Dalhousie", slug: "dalhousie" },
  { name: "Dharamsala", slug: "dharamsala" },
  { name: "Hamirpur", slug: "hamirpur" },
  { name: "Kangra", slug: "kangra" },
  { name: "Mandi", slug: "mandi" },
  { name: "Nahan", slug: "nahan" },
  { name: "Palampur", slug: "palampur" },
  { name: "Shimla", slug: "shimla" },
  { name: "Solan", slug: "solan" },
  { name: "Sundarnagar", slug: "sundarnagar" },
  { name: "Una", slug: "una" },
];

export const Jammu_Kashmir = [
  { name: "Anantnag", slug: "anantnag" },
  { name: "Baramula", slug: "baramula" },
  { name: "Budgam", slug: "budgam" },
  { name: "Doda", slug: "doda" },
  { name: "Gulmarg", slug: "gulmarg" },
  { name: "Jammu", slug: "jammu" },
  { name: "Kargil", slug: "kargil" },
  { name: "Leh", slug: "leh" },
  { name: "Punch", slug: "punch" },
  { name: "Rajauri", slug: "rajauri" },
  { name: "Srinagar", slug: "srinagar" },
  { name: "Udhampur", slug: "udhampur" },
];

export const Jharkhand = [
  { name: "Bokaro", slug: "bokaro" },
  { name: "Chaibasa", slug: "chaibasa" },
  { name: "Chatra", slug: "chatra" },
  { name: "Deoghar", slug: "deoghar" },
  { name: "Dhanbad", slug: "dhanbad" },
  { name: "Dumka", slug: "dumka" },
  { name: "Giridih", slug: "giridih" },
  { name: "Hazaribag", slug: "hazaribag" },
  { name: "Jamshedpur", slug: "jamshedpur" },
  { name: "Jhumri Tilaiya", slug: "jhumri-tilaiya" },
  { name: "Lohardaga", slug: "lohardaga" },
  { name: "Madhupur", slug: "madhupur" },
  { name: "Mango", slug: "mango" },
  { name: "Pakaur", slug: "pakaur" },
  { name: "Patratu", slug: "patratu" },
  { name: "Phusro", slug: "phusro" },
  { name: "Ramgarh", slug: "ramgarh" },
  { name: "Ranchi", slug: "ranchi" },
  { name: "Saunda", slug: "saunda" },
  { name: "Simdega", slug: "simdega" },
];

export const Karnataka = [
  { name: "Adyar", slug: "adyar" },
  { name: "Afzalpur", slug: "afzalpur" },
  { name: "Aland", slug: "aland" },
  { name: "Alur", slug: "alur" },
  { name: "Alwar", slug: "alwar" },
  { name: "Ambur", slug: "ambur" },
  { name: "Amravati", slug: "amravati" },
  { name: "Anantapur", slug: "anantapur" },
  { name: "Arakkonam", slug: "arakkonam" },
  { name: "Arkalgud", slug: "arkalgud" },
  { name: "Arsikere", slug: "arsikere" },
  { name: "Athni", slug: "athni" },
  { name: "Aurad", slug: "aurad" },
  { name: "Badami", slug: "badami" },
  { name: "Bagalkot", slug: "bagalkot" },
  { name: "Bagepalli", slug: "bagepalli" },
  { name: "Balaghat", slug: "balaghat" },
  { name: "Ballari", slug: "ballari" },
  { name: "Bangalore", slug: "bangalore" },
  { name: "Bangarapet", slug: "bangarapet" },
  { name: "Bankapura", slug: "bankapura" },
  { name: "Belgaum", slug: "belgaum" },
  { name: "Bellary", slug: "bellary" },
  { name: "Belthangady", slug: "belthangady" },
  { name: "Bengaluru", slug: "bengaluru" },
  { name: "Bhadravati", slug: "bhadravati" },
  { name: "Bhalki", slug: "bhalki" },
  { name: "Bhatkal", slug: "bhatkal" },
  { name: "Bhimarayanagudi", slug: "bhimarayanagudi" },
  { name: "Bhongir", slug: "bhongir" },
  { name: "Bidar", slug: "bidar" },
  { name: "Bijapur", slug: "bijapur" },
  { name: "Bijapur", slug: "bijapur" },
  { name: "Bilgi", slug: "bilgi" },
  { name: "Birur", slug: "birur" },
  { name: "Bommanahalli", slug: "bommanahalli" },
  { name: "Bommasandra", slug: "bommasandra" },
  { name: "Byadgi", slug: "byadgi" },
  { name: "Challakere", slug: "challakere" },
  { name: "Chamarajanagar", slug: "chamarajanagar" },
  { name: "Chamrajnagar", slug: "chamrajnagar" },
  { name: "Channagiri", slug: "channagiri" },
  { name: "Channapatna", slug: "channapatna" },
  { name: "Channarayapatna", slug: "channarayapatna" },
  { name: "Chickballapur", slug: "chickballapur" },
  { name: "Chikmagalur", slug: "chikmagalur" },
  { name: "Chiknayakanhalli", slug: "chiknayakanhalli" },
  { name: "Chintamani", slug: "chintamani" },
  { name: "Chitradurga", slug: "chitradurga" },
  { name: "Chitradurga", slug: "chitradurga" },
  { name: "Chitradurga", slug: "chitradurga" },
  { name: "Chitradurga", slug: "chitradurga" },
  { name: "Chittapur", slug: "chittapur" },
  { name: "Chittapur", slug: "chittapur" },
  { name: "Chittur-Thathamangalam", slug: "chittur-thathamangalam" },
  { name: "Chowdeshwari", slug: "chowdeshwari" },
  { name: "Chunchanagiri", slug: "chunchanagiri" },
  { name: "Coleyar", slug: "coleyar" },
  { name: "Davanagere", slug: "davanagere" },
  { name: "Devadurga", slug: "devadurga" },
  { name: "Devanhalli", slug: "devanhalli" },
  { name: "Dharwad", slug: "dharwad" },
  { name: "Dharmavaram", slug: "dharmavaram" },
  { name: "Holalkere", slug: "holalkere" },
  { name: "Honnali", slug: "honnali" },
  { name: "Honnavar", slug: "honnavar" },
  { name: "Hubli-Dharwad", slug: "hubli-dharwad" },
  { name: "Hungund", slug: "hungund" },
  { name: "Hunsur", slug: "hunsur" },
  { name: "Huvina Hadagali", slug: "huvina-hadagali" },
  { name: "Ilkal", slug: "ilkal" },
  { name: "Indi", slug: "indi" },
  { name: "Jagalur", slug: "jagalur" },
  { name: "Jamkhandi", slug: "jamkhandi" },
  { name: "Jevargi", slug: "jevargi" },
  { name: "Joida", slug: "joida" },
  { name: "Kadur", slug: "kadur" },
  { name: "Kalghatgi", slug: "kalghatgi" },
  { name: "Kalluru", slug: "kalluru" },
  { name: "Kalpetta", slug: "kalpetta" },
  { name: "Kamalapuram", slug: "kamalapuram" },
  { name: "Kampli", slug: "kampli" },
  { name: "Kampli", slug: "kampli" },
  { name: "Kanakapura", slug: "kanakapura" },
  { name: "Kanakapura", slug: "kanakapura" },
  { name: "Kanhangad", slug: "kanhangad" },
  { name: "Karkala", slug: "karkala" },
  { name: "Karwar", slug: "karwar" },
  { name: "Kasaragod", slug: "kasaragod" },
  { name: "Kasargod", slug: "kasargod" },
  { name: "Kathriguppe", slug: "kathriguppe" },
  { name: "Katpadi", slug: "katpadi" },
  { name: "Kavalur", slug: "kavalur" },
  { name: "Kavali", slug: "kavali" },
  { name: "Kayamkulam", slug: "kayamkulam" },
  { name: "Kempegowda Nagar", slug: "kempegowda-nagar" },
  { name: "Kengeri", slug: "kengeri" },
  { name: "Kerur", slug: "kerur" },
  { name: "Khanapur", slug: "khanapur" },
  { name: "Kodigenahalli", slug: "kodigenahalli" },
  { name: "Kolar", slug: "kolar" },
  { name: "Kolar", slug: "kolar" },
  { name: "Kollegal", slug: "kollegal" },
  { name: "Konnur", slug: "konnur" },
  { name: "Koppal", slug: "koppal" },
  { name: "Koratagere", slug: "koratagere" },
  { name: "Koratla", slug: "koratla" },
  { name: "Kotturu", slug: "kotturu" },
  { name: "Kovvur", slug: "kovvur" },
  { name: "Krishnarajpet", slug: "krishnarajpet" },
  { name: "Kudligi", slug: "kudligi" },
  { name: "Kudligi", slug: "kudligi" },
  { name: "Kuknoor", slug: "kuknoor" },
  { name: "Kumta", slug: "kumta" },
  { name: "Kundapura", slug: "kundapura" },
  { name: "Kunigal", slug: "kunigal" },
  { name: "Kurgunta", slug: "kurgunta" },
  { name: "Kushtagi", slug: "kushtagi" },
  { name: "Lakshmeshwar", slug: "lakshmeshwar" },
];

export const Kerala = [
  { name: "Alappuzha", slug: "alappuzha" },
  { name: "Attingal", slug: "attingal" },
  { name: "Chalakudy", slug: "chalakudy" },
  { name: "Changanassery", slug: "changanassery" },
  { name: "Chendamangalam", slug: "chendamangalam" },
  { name: "Chengannur", slug: "chengannur" },
  { name: "Cherthala", slug: "cherthala" },
  { name: "Chittur-Thathamangalam", slug: "chittur-thathamangalam" },
  { name: "Erattupetta", slug: "erattupetta" },
  { name: "Guruvayur", slug: "guruvayur" },
  { name: "Kanhangad", slug: "kanhangad" },
  { name: "Kannur", slug: "kannur" },
  { name: "Kayamkulam", slug: "kayamkulam" },
  { name: "Kochi", slug: "kochi" },
  { name: "Kodungallur", slug: "kodungallur" },
  { name: "Kollam", slug: "kollam" },
  { name: "Kottayam", slug: "kottayam" },
  { name: "Kozhikode", slug: "kozhikode" },
  { name: "Kunnamkulam", slug: "kunnamkulam" },
  { name: "Malappuram", slug: "malappuram" },
  { name: "Mattannur", slug: "mattannur" },
  { name: "Mavelikkara", slug: "mavelikkara" },
  { name: "Mavoor", slug: "mavoor" },
  { name: "Muvattupuzha", slug: "muvattupuzha" },
  { name: "Nedumangad", slug: "nedumangad" },
  { name: "Neyyattinkara", slug: "neyyattinkara" },
  { name: "Nilambur", slug: "nilambur" },
  { name: "Ottappalam", slug: "ottappalam" },
  { name: "Palai", slug: "palai" },
  { name: "Palakkad", slug: "palakkad" },
  { name: "Panniyannur", slug: "panniyannur" },
  { name: "Pappinisseri", slug: "pappinisseri" },
  { name: "Paravoor", slug: "paravoor" },
  { name: "Pathanamthitta", slug: "pathanamthitta" },
  { name: "Peringathur", slug: "peringathur" },
  { name: "Perinthalmanna", slug: "perinthalmanna" },
  { name: "Perumbavoor", slug: "perumbavoor" },
  { name: "Ponnani", slug: "ponnani" },
  { name: "Punalur", slug: "punalur" },
  { name: "Quilandy", slug: "quilandy" },
  { name: "Shoranur", slug: "shoranur" },
  { name: "Taliparamba", slug: "taliparamba" },
  { name: "Thiruvalla", slug: "thiruvalla" },
  { name: "Thiruvananthapuram", slug: "thiruvananthapuram" },
  { name: "Thodupuzha", slug: "thodupuzha" },
  { name: "Thrissur", slug: "thrissur" },
  { name: "Tirur", slug: "tirur" },
  { name: "Vaikom", slug: "vaikom" },
  { name: "Varkala", slug: "varkala" },
  { name: "Vatakara", slug: "vatakara" },
];

export const Madhya_Pradesh = [
  { name: "Alirajpur", slug: "alirajpur" },
  { name: "Anuppur", slug: "anuppur" },
  { name: "Ashoknagar", slug: "ashoknagar" },
  { name: "Balaghat", slug: "balaghat" },
  { name: "Barwani", slug: "barwani" },
  { name: "Betul", slug: "betul" },
  { name: "Bhind", slug: "bhind" },
  { name: "Bhopal", slug: "bhopal" },
  { name: "Burhanpur", slug: "burhanpur" },
  { name: "Chhatarpur", slug: "chhatarpur" },
  { name: "Chhindwara", slug: "chhindwara" },
  { name: "Damoh", slug: "damoh" },
  { name: "Datia", slug: "datia" },
  { name: "Dewas", slug: "dewas" },
  { name: "Dhar", slug: "dhar" },
  { name: "Dindori", slug: "dindori" },
  { name: "Guna", slug: "guna" },
  { name: "Gwalior", slug: "gwalior" },
  { name: "Harda", slug: "harda" },
  { name: "Hoshangabad", slug: "hoshangabad" },
  { name: "Indore", slug: "indore" },
  { name: "Jabalpur", slug: "jabalpur" },
  { name: "Jhabua", slug: "jhabua" },
  { name: "Katni", slug: "katni" },
  { name: "Khandwa", slug: "khandwa" },
  { name: "Khargone", slug: "khargone" },
  { name: "Mandla", slug: "mandla" },
  { name: "Mandsaur", slug: "mandsaur" },
  { name: "Morena", slug: "morena" },
  { name: "Narsinghpur", slug: "narsinghpur" },
  { name: "Neemuch", slug: "neemuch" },
  { name: "Panna", slug: "panna" },
  { name: "Raisen", slug: "raisen" },
  { name: "Rajgarh", slug: "rajgarh" },
  { name: "Ratlam", slug: "ratlam" },
  { name: "Rewa", slug: "rewa" },
  { name: "Sagar", slug: "sagar" },
  { name: "Satna", slug: "satna" },
  { name: "Sehore", slug: "sehore" },
  { name: "Seoni", slug: "seoni" },
  { name: "Shahdol", slug: "shahdol" },
  { name: "Shajapur", slug: "shajapur" },
  { name: "Sheopur", slug: "sheopur" },
  { name: "Shivpuri", slug: "shivpuri" },
  { name: "Sidhi", slug: "sidhi" },
  { name: "Singrauli", slug: "singrauli" },
  { name: "Tikamgarh", slug: "tikamgarh" },
  { name: "Ujjain", slug: "ujjain" },
  { name: "Umaria", slug: "umaria" },
  { name: "Vidisha", slug: "vidisha" },
];

export const Maharashtra = [
  { name: "Ahmednagar", slug: "ahmednagar" },
  { name: "Akola", slug: "akola" },
  { name: "Amravati", slug: "amravati" },
  { name: "Aurangabad", slug: "aurangabad" },
  { name: "Beed", slug: "beed" },
  { name: "Bhandara", slug: "bhandara" },
  { name: "Buldhana", slug: "buldhana" },
  { name: "Chandrapur", slug: "chandrapur" },
  { name: "Dhule", slug: "dhule" },
  { name: "Gadchiroli", slug: "gadchiroli" },
  { name: "Gondia", slug: "gondia" },
  { name: "Hingoli", slug: "hingoli" },
  { name: "Jalgaon", slug: "jalgaon" },
  { name: "Jalna", slug: "jalna" },
  { name: "Kolhapur", slug: "kolhapur" },
  { name: "Latur", slug: "latur" },
  { name: "Mumbai", slug: "mumbai" },
  { name: "Mumbai Suburban", slug: "mumbai-suburban" },
  { name: "Nagpur", slug: "nagpur" },
  { name: "Nanded", slug: "nanded" },
  { name: "Nandurbar", slug: "nandurbar" },
  { name: "Nashik", slug: "nashik" },
  { name: "Osmanabad", slug: "osmanabad" },
  { name: "Palghar", slug: "palghar" },
  { name: "Parbhani", slug: "parbhani" },
  { name: "Pune", slug: "pune" },
  { name: "Raigad", slug: "raigad" },
  { name: "Ratnagiri", slug: "ratnagiri" },
  { name: "Sangli", slug: "sangli" },
  { name: "Satara", slug: "satara" },
  { name: "Sindhudurg", slug: "sindhudurg" },
  { name: "Solapur", slug: "solapur" },
  { name: "Thane", slug: "thane" },
  { name: "Wardha", slug: "wardha" },
  { name: "Washim", slug: "washim" },
  { name: "Yavatmal", slug: "yavatmal" },
];

export const Manipur = [
  { name: "Bishnupur", slug: "bishnupur" },
  { name: "Chandel", slug: "chandel" },
  { name: "Churachandpur", slug: "churachandpur" },
  { name: "Imphal East", slug: "imphal-east" },
  { name: "Imphal West", slug: "imphal-west" },
  { name: "Senapati", slug: "senapati" },
  { name: "Tamenglong", slug: "tamenglong" },
  { name: "Thoubal", slug: "thoubal" },
  { name: "Ukhrul", slug: "ukhrul" },
];

export const Meghalaya = [
  { name: "East Garo Hills", slug: "east-garo-hills" },
  { name: "East Jaintia Hills", slug: "east-jaintia-hills" },
  { name: "East Khasi Hills", slug: "east-khasi-hills" },
  { name: "North Garo Hills", slug: "north-garo-hills" },
  { name: "Ri Bhoi", slug: "ri-bhoi" },
  { name: "South Garo Hills", slug: "south-garo-hills" },
  { name: "South West Garo Hills", slug: "south-west-garo-hills" },
  { name: "South West Khasi Hills", slug: "south-west-khasi-hills" },
  { name: "West Garo Hills", slug: "west-garo-hills" },
  { name: "West Jaintia Hills", slug: "west-jaintia-hills" },
  { name: "West Khasi Hills", slug: "west-khasi-hills" },
];

export const Mizoram = [
  { name: "Aizawl", slug: "aizawl" },
  { name: "Champhai", slug: "champhai" },
  { name: "Kolasib", slug: "kolasib" },
  { name: "Lawngtlai", slug: "lawngtlai" },
  { name: "Lunglei", slug: "lunglei" },
  { name: "Mamit", slug: "mamit" },
  { name: "Saiha", slug: "saiha" },
  { name: "Serchhip", slug: "serchhip" },
];

export const Nagaland = [
  { name: "Dimapur", slug: "dimapur" },
  { name: "Kiphire", slug: "kiphire" },
  { name: "Kohima", slug: "kohima" },
  { name: "Longleng", slug: "longleng" },
  { name: "Mokokchung", slug: "mokokchung" },
  { name: "Mon", slug: "mon" },
  { name: "Peren", slug: "peren" },
  { name: "Phek", slug: "phek" },
  { name: "Tuensang", slug: "tuensang" },
  { name: "Wokha", slug: "wokha" },
  { name: "Zunheboto", slug: "zunheboto" },
];

export const Odisha = [
  { name: "Angul", slug: "angul" },
  { name: "Balangir", slug: "balangir" },
  { name: "Balasore", slug: "balasore" },
  { name: "Bargarh", slug: "bargarh" },
  { name: "Bhadrak", slug: "bhadrak" },
  { name: "Boudh", slug: "boudh" },
  { name: "Cuttack", slug: "cuttack" },
  { name: "Debagarh", slug: "debagarh" },
  { name: "Dhenkanal", slug: "dhenkanal" },
  { name: "Gajapati", slug: "gajapati" },
  { name: "Ganjam", slug: "ganjam" },
  { name: "Jagatsinghpur", slug: "jagatsinghpur" },
  { name: "Jajpur", slug: "jajpur" },
  { name: "Jharsuguda", slug: "jharsuguda" },
  { name: "Kalahandi", slug: "kalahandi" },
  { name: "Kandhamal", slug: "kandhamal" },
  { name: "Kendrapara", slug: "kendrapara" },
  { name: "Kendujhar", slug: "kendujhar" },
  { name: "Khordha", slug: "khordha" },
  { name: "Koraput", slug: "koraput" },
  { name: "Malkangiri", slug: "malkangiri" },
  { name: "Mayurbhanj", slug: "mayurbhanj" },
  { name: "Nabarangpur", slug: "nabarangpur" },
  { name: "Nayagarh", slug: "nayagarh" },
  { name: "Nuapada", slug: "nuapada" },
  { name: "Puri", slug: "puri" },
  { name: "Rayagada", slug: "rayagada" },
  { name: "Sambalpur", slug: "sambalpur" },
  { name: "Sonepur", slug: "sonepur" },
  { name: "Sundargarh", slug: "sundargarh" },
];

export const Punjab = [
  { name: "Amritsar", slug: "amritsar" },
  { name: "Barnala", slug: "barnala" },
  { name: "Bathinda", slug: "bathinda" },
  { name: "Faridkot", slug: "faridkot" },
  { name: "Fatehgarh Sahib", slug: "fatehgarh-sahib" },
  { name: "Fazilka", slug: "fazilka" },
  { name: "Ferozepur", slug: "ferozepur" },
  { name: "Gurdaspur", slug: "gurdaspur" },
  { name: "Hoshiarpur", slug: "hoshiarpur" },
  { name: "Jalandhar", slug: "jalandhar" },
  { name: "Kapurthala", slug: "kapurthala" },
  { name: "Ludhiana", slug: "ludhiana" },
  { name: "Mansa", slug: "mansa" },
  { name: "Moga", slug: "moga" },
  { name: "Muktsar", slug: "muktsar" },
  { name: "Nawanshahr", slug: "nawanshahr" },
  { name: "Pathankot", slug: "pathankot" },
  { name: "Patiala", slug: "patiala" },
  { name: "Rupnagar", slug: "rupnagar" },
  { name: "Sangrur", slug: "sangrur" },
  {
    name: "Shaheed Bhagat Singh Nagar",
    slug: "shaheed-bhagat-singh-nagar",
  },
  { name: "Tarn Taran", slug: "tarn-taran" },
];

export const Rajasthan = [
  { name: "Ajmer", slug: "ajmer" },
  { name: "Alwar", slug: "alwar" },
  { name: "Banswara", slug: "banswara" },
  { name: "Baran", slug: "baran" },
  { name: "Barmer", slug: "barmer" },
  { name: "Bharatpur", slug: "bharatpur" },
  { name: "Bhilwara", slug: "bhilwara" },
  { name: "Bikaner", slug: "bikaner" },
  { name: "Bundi", slug: "bundi" },
  { name: "Chittorgarh", slug: "chittorgarh" },
  { name: "Churu", slug: "churu" },
  { name: "Dausa", slug: "dausa" },
  { name: "Dholpur", slug: "dholpur" },
  { name: "Dungarpur", slug: "dungarpur" },
  { name: "Hanumangarh", slug: "hanumangarh" },
  { name: "Jaipur", slug: "jaipur" },
  { name: "Jaisalmer", slug: "jaisalmer" },
  { name: "Jalore", slug: "jalore" },
  { name: "Jhalawar", slug: "jhalawar" },
  { name: "Jhunjhunu", slug: "jhunjhunu" },
  { name: "Jodhpur", slug: "jodhpur" },
  { name: "Karauli", slug: "karauli" },
  { name: "Kota", slug: "kota" },
  { name: "Nagaur", slug: "nagaur" },
  { name: "Pali", slug: "pali" },
  { name: "Pratapgarh", slug: "pratapgarh" },
  { name: "Rajsamand", slug: "rajsamand" },
  { name: "Sawai Madhopur", slug: "sawai-madhopur" },
  { name: "Sikar", slug: "sikar" },
  { name: "Sirohi", slug: "sirohi" },
  { name: "Tonk", slug: "tonk" },
  { name: "Udaipur", slug: "udaipur" },
];

export const Sikkim = [
  { name: "East Sikkim", slug: "east-sikkim" },
  { name: "North Sikkim", slug: "north-sikkim" },
  { name: "South Sikkim", slug: "south-sikkim" },
  { name: "West Sikkim", slug: "west-sikkim" },
];

export const Tamil_Nadu = [
  { name: "Ariyalur", slug: "ariyalur" },
  { name: "Chengalpattu", slug: "chengalpattu" },
  { name: "Chennai", slug: "chennai" },
  { name: "Coimbatore", slug: "coimbatore" },
  { name: "Cuddalore", slug: "cuddalore" },
  { name: "Dharmapuri", slug: "dharmapuri" },
  { name: "Dindigul", slug: "dindigul" },
  { name: "Erode", slug: "erode" },
  { name: "Kallakurichi", slug: "kallakurichi" },
  { name: "Kanchipuram", slug: "kanchipuram" },
  { name: "Kanyakumari", slug: "kanyakumari" },
  { name: "Karur", slug: "karur" },
  { name: "Krishnagiri", slug: "krishnagiri" },
  { name: "Madurai", slug: "madurai" },
  { name: "Mayiladuthurai", slug: "mayiladuthurai" },
  { name: "Nagapattinam", slug: "nagapattinam" },
  { name: "Namakkal", slug: "namakkal" },
  { name: "Nilgiris", slug: "nilgiris" },
  { name: "Perambalur", slug: "perambalur" },
  { name: "Pudukkottai", slug: "pudukkottai" },
  { name: "Ramanathapuram", slug: "ramanathapuram" },
  { name: "Ranipet", slug: "ranipet" },
  { name: "Salem", slug: "salem" },
  { name: "Sivaganga", slug: "sivaganga" },
  { name: "Tenkasi", slug: "tenkasi" },
  { name: "Thanjavur", slug: "thanjavur" },
  { name: "Theni", slug: "theni" },
  { name: "Thoothukudi", slug: "thoothukudi" },
  { name: "Tiruchirappalli", slug: "tiruchirappalli" },
  { name: "Tirunelveli", slug: "tirunelveli" },
  { name: "Tirupathur", slug: "tirupathur" },
  { name: "Tiruppur", slug: "tiruppur" },
  { name: "Tiruvallur", slug: "tiruvallur" },
  { name: "Tiruvannamalai", slug: "tiruvannamalai" },
  { name: "Tiruvarur", slug: "tiruvarur" },
  { name: "Vellore", slug: "vellore" },
  { name: "Viluppuram", slug: "viluppuram" },
  { name: "Virudhunagar", slug: "virudhunagar" },
];

export const Telangana = [
  { name: "Adilabad", slug: "adilabad" },
  { name: "Bhadradri Kothagudem", slug: "bhadradri-kothagudem" },
  { name: "Hyderabad", slug: "hyderabad" },
  { name: "Jagtial", slug: "jagtial" },
  { name: "Jangaon", slug: "jangaon" },
  {
    name: "Jayashankar Bhupalapally",
    slug: "jayashankar-bhupalapally",
  },
  { name: "Jogulamba Gadwal", slug: "jogulamba-gadwal" },
  { name: "Kamareddy", slug: "kamareddy" },
  { name: "Karimnagar", slug: "karimnagar" },
  { name: "Khammam", slug: "khammam" },
  { name: "Komaram Bheem", slug: "komaram-bheem" },
  { name: "Mahabubabad", slug: "mahabubabad" },
  { name: "Mahabubnagar", slug: "mahabubnagar" },
  { name: "Mancherial", slug: "mancherial" },
  { name: "Medak", slug: "medak" },
  { name: "Medchal", slug: "medchal" },
  { name: "Nagarkurnool", slug: "nagarkurnool" },
  { name: "Nalgonda", slug: "nalgonda" },
  { name: "Nirmal", slug: "nirmal" },
  { name: "Nizamabad", slug: "nizamabad" },
  { name: "Peddapalli", slug: "peddapalli" },
  { name: "Rajanna Sircilla", slug: "rajanna-sircilla" },
  { name: "Rangareddy", slug: "rangareddy" },
  { name: "Sangareddy", slug: "sangareddy" },
  { name: "Siddipet", slug: "siddipet" },
  { name: "Suryapet", slug: "suryapet" },
  { name: "Vikarabad", slug: "vikarabad" },
  { name: "Wanaparthy", slug: "wanaparthy" },
  { name: "Warangal Rurban", slug: "warangal-rurban" },
  { name: "Warangal Urban", slug: "warangal-urban" },
  { name: "Yadadri Bhuvanagiri", slug: "yadadri-bhuvanagiri" },
];

export const Tripura = [
  { name: "Dhalai", slug: "dhalai" },
  { name: "Gomati", slug: "gomati" },
  { name: "Khowai", slug: "khowai" },
  { name: "North Tripura", slug: "north-tripura" },
  { name: "Sepahijala", slug: "sepahijala" },
  { name: "South Tripura", slug: "south-tripura" },
  { name: "Unakoti", slug: "unakoti" },
  { name: "West Tripura", slug: "west-tripura" },
];

export const Uttar_Pradesh = [
  { name: "Agra", slug: "agra" },
  { name: "Aligarh", slug: "aligarh" },
  { name: "Ambedkar Nagar", slug: "ambedkar-nagar" },
  { name: "Amethi", slug: "amethi" },
  { name: "Amroha", slug: "amroha" },
  { name: "Auraiya", slug: "auraiya" },
  { name: "Ayodhya", slug: "ayodhya" },
  { name: "Azamgarh", slug: "azamgarh" },
  { name: "Baghpat", slug: "baghpat" },
  { name: "Bahraich", slug: "bahraich" },
  { name: "Ballia", slug: "ballia" },
  { name: "Balrampur", slug: "balrampur" },
  { name: "Banda", slug: "banda" },
  { name: "Barabanki", slug: "barabanki" },
  { name: "Bareilly", slug: "bareilly" },
  { name: "Basti", slug: "basti" },
  { name: "Bhadohi", slug: "bhadohi" },
  { name: "Bijnor", slug: "bijnor" },
  { name: "Budaun", slug: "budaun" },
  { name: "Bulandshahr", slug: "bulandshahr" },
  { name: "Chandauli", slug: "chandauli" },
  { name: "Chitrakoot", slug: "chitrakoot" },
  { name: "Deoria", slug: "deoria" },
  { name: "Etah", slug: "etah" },
  { name: "Etawah", slug: "etawah" },
  { name: "Faizabad", slug: "faizabad" },
  { name: "Farrukhabad", slug: "farrukhabad" },
  { name: "Fatehpur", slug: "fatehpur" },
  { name: "Firozabad", slug: "firozabad" },
  { name: "Gautam Buddha Nagar", slug: "gautam-buddha-nagar" },
  { name: "Ghaziabad", slug: "ghaziabad" },
  { name: "Ghazipur", slug: "ghazipur" },
  { name: "Gonda", slug: "gonda" },
  { name: "Gorakhpur", slug: "gorakhpur" },
  { name: "Hamirpur", slug: "hamirpur" },
  { name: "Hapur", slug: "hapur" },
  { name: "Hardoi", slug: "hardoi" },
  { name: "Hathras", slug: "hathras" },
  { name: "Jalaun", slug: "jalaun" },
  { name: "Jaunpur", slug: "jaunpur" },
  { name: "Jhansi", slug: "jhansi" },
  { name: "Kannauj", slug: "kannauj" },
  { name: "Kanpur Dehat", slug: "kanpur-dehat" },
  { name: "Kanpur Nagar", slug: "kanpur-nagar" },
  { name: "Kasganj", slug: "kasganj" },
  { name: "Kaushambi", slug: "kaushambi" },
  { name: "Kushinagar", slug: "kushinagar" },
  { name: "Lakhimpur Kheri", slug: "lakhimpur-kheri" },
  { name: "Lalitpur", slug: "lalitpur" },
  { name: "Lucknow", slug: "lucknow" },
  { name: "Maharajganj", slug: "maharajganj" },
  { name: "Mahoba", slug: "mahoba" },
  { name: "Mainpuri", slug: "mainpuri" },
  { name: "Mathura", slug: "mathura" },
  { name: "Mau", slug: "mau" },
  { name: "Meerut", slug: "meerut" },
  { name: "Mirzapur", slug: "mirzapur" },
  { name: "Moradabad", slug: "moradabad" },
  { name: "Muzaffarnagar", slug: "muzaffarnagar" },
  { name: "Pilibhit", slug: "pilibhit" },
  { name: "Pratapgarh", slug: "pratapgarh" },
  { name: "RaeBareli", slug: "raebareli" },
  { name: "Rampur", slug: "rampur" },
  { name: "Saharanpur", slug: "saharanpur" },
  { name: "Sambhal", slug: "sambhal" },
  { name: "Sant Kabir Nagar", slug: "sant-kabir-nagar" },
  { name: "Shahjahanpur", slug: "shahjahanpur" },
  { name: "Shamli", slug: "shamli" },
  { name: "Shravasti", slug: "shravasti" },
  { name: "Siddharthnagar", slug: "siddharthnagar" },
  { name: "Sitapur", slug: "sitapur" },
  { name: "Sonbhadra", slug: "sonbhadra" },
  { name: "Sultanpur", slug: "sultanpur" },
  { name: "Unnao", slug: "unnao" },
  { name: "Varanasi", slug: "varanasi" },
];

export const Uttarakhand = [
  { name: "Almora", slug: "almora" },
  { name: "Bageshwar", slug: "bageshwar" },
  { name: "Chamoli", slug: "chamoli" },
  { name: "Champawat", slug: "champawat" },
  { name: "Dehradun", slug: "dehradun" },
  { name: "Haridwar", slug: "haridwar" },
  { name: "Nainital", slug: "nainital" },
  { name: "Pauri Garhwal", slug: "pauri-garhwal" },
  { name: "Pithoragarh", slug: "pithoragarh" },
  { name: "Rudraprayag", slug: "rudraprayag" },
  { name: "Tehri Garhwal", slug: "tehri-garhwal" },
  { name: "Udham Singh Nagar", slug: "udham-singh-nagar" },
  { name: "Uttarkashi", slug: "uttarkashi" },
];

export const West_Bengal = [
  { name: "Alipurduar", slug: "alipurduar" },
  { name: "Bankura", slug: "bankura" },
  { name: "Birbhum", slug: "birbhum" },
  { name: "Cooch Behar", slug: "cooch-behar" },
  { name: "Dakshin Dinajpur", slug: "dakshin-dinajpur" },
  { name: "Darjeeling", slug: "darjeeling" },
  { name: "Hooghly", slug: "hooghly" },
  { name: "Howrah", slug: "howrah" },
  { name: "Jalpaiguri", slug: "jalpaiguri" },
  { name: "Jhargram", slug: "jhargram" },
  { name: "Kalimpong", slug: "kalimpong" },
  { name: "Kolkata", slug: "kolkata" },
  { name: "Malda", slug: "malda" },
  { name: "Murshidabad", slug: "murshidabad" },
  { name: "Nadia", slug: "nadia" },
  { name: "North 24 Parganas", slug: "north-24-parganas" },
  { name: "Paschim Medinipur", slug: "paschim-medinipur" },
  { name: "Purba Medinipur", slug: "purba-medinipur" },
  { name: "Purulia", slug: "purulia" },
  { name: "South 24 Parganas", slug: "south-24-parganas" },
  { name: "Uttar Dinajpur", slug: "uttar-dinajpur" },
];

export const States = [
  {
    name: "Andhra Pradesh",
    slug: "andhra-pradesh",
    districts: Andhra_Pradesh,
  },
  {
    name: "Arunachal Pradesh",
    slug: "arunachal-pradesh",
    districts: Arunachal_Pradesh,
  },
  {
    name: "Assam",
    slug: "assam",
    districts: Assam,
  },
  {
    name: "Bihar",
    slug: "bihar",
    districts: Bihar,
  },
  {
    name: "Chhattisgarh",
    slug: "chhattisgarh",
    districts: Chhattisgarh,
  },
  {
    name: "Goa",
    slug: "goa",
    districts: Goa,
  },
  {
    name: "Gujarat",
    slug: "gujarat",
    districts: Gujarat,
  },
  {
    name: "Haryana",
    slug: "haryana",
    districts: Haryana,
  },
  {
    name: "Himachal Pradesh",
    slug: "himachal-pradesh",
    districts: Himachal_Pradesh,
  },
  {
    name: "Jharkhand",
    slug: "jharkhand",
    districts: Jharkhand,
  },
  {
    name: "Karnataka",
    slug: "karnataka",
    districts: Karnataka,
  },
  {
    name: "Kerala",
    slug: "kerala",
    districts: Kerala,
  },
  {
    name: "Madhya Pradesh",
    slug: "madhya-pradesh",
    districts: Madhya_Pradesh,
  },
  {
    name: "Maharashtra",
    slug: "maharashtra",
    districts: Maharashtra,
  },
  {
    name: "Manipur",
    slug: "manipur",
    districts: Manipur,
  },
  {
    name: "Meghalaya",
    slug: "meghalaya",
    districts: Meghalaya,
  },
  {
    name: "Mizoram",
    slug: "mizoram",
    districts: Mizoram,
  },
  {
    name: "Nagaland",
    slug: "nagaland",
    districts: Nagaland,
  },
  {
    name: "Odisha",
    slug: "odisha",
    districts: Odisha,
  },
  {
    name: "Punjab",
    slug: "punjab",
    districts: Punjab,
  },
  {
    name: "Rajasthan",
    slug: "rajasthan",
    districts: Rajasthan,
  },
  {
    name: "Sikkim",
    slug: "sikkim",
    districts: Sikkim,
  },
  {
    name: "Tamil Nadu",
    slug: "tamil-nadu",
    districts: Tamil_Nadu,
  },
  {
    name: "Telangana",
    slug: "telangana",
    districts: Telangana,
  },
  {
    name: "Tripura",
    slug: "tripura",
    districts: Tripura,
  },
  {
    name: "Uttar Pradesh",
    slug: "uttar-pradesh",
    districts: Uttar_Pradesh,
  },
  {
    name: "Uttarakhand",
    slug: "uttarakhand",
    districts: Uttarakhand,
  },
  {
    name: "West Bengal",
    slug: "west-bengal",
    districts: West_Bengal,
  },
];

export const WeddingCategoryDesContent = [
  {
    title: "Wedding Planner",
    slug: "wedding-planner",
    info: " Skilled wedding planners are capable of designing a stunning and remarkable space that complements your chosen theme.",
    img1: "2",
    img2: "5",
    descriptionA:
      "A couple's wedding is an incredibly emotional occasion that is celebrated with various traditions and events in Indian culture. However, it can be overwhelming for couples to manage all of these events and achieve the perfect vision for their special day. When planning a wedding, couples are faced with the difficult decision of choosing between various options. They must find a suitable location, wedding planners, interior designers, and catering services that offer a range of cuisines. Additionally, choosing elegant attire, such as bridal lehengas, wedding jewelry, and Mehendi artists to adorn their hands, is crucial. A wedding is a cherished memory that will be treasured for a lifetime. ",
    descriptionB:
      "When it comes to finding the perfect wedding planner for your big day, look no further than WeddingPlanner. Their extensive list of options allows you to easily browse and discover the ideal planner with just a few clicks. Visiting their website will put your mind at ease, as you can entrust the responsibility of achieving perfection to experienced professionals. With their guidance, you'll be able to enjoy your special day to the fullest without having to stress over the minor details.",
  },
  {
    title: "Wedding Decoration",
    slug: "wedding-decoration",
    info: "Whether you desire floral arrangements and decorations, coordinated color schemes, or a beautifully lit mandap, they have everything covered.",
    img1: "1",
    img2: "3",
    descriptionA:
      "Wedding themes add excitement and create lasting memories for the special day. Skilled wedding planners are capable of designing a stunning and remarkable space that complements your chosen theme. Whether you desire floral arrangements and decorations, coordinated color schemes, or a beautifully lit mandap, they have everything covered to make your dream wedding a reality. This will undoubtedly evoke strong emotions and leave a lasting impression on you and your guests.",
    descriptionB:
      "Wedding Planners offers a wide range of services that can be personalized and customized as per your needs and references. The list of services offered are:",
    list: [
      "Ideation & design",
      "Lighting",
      "Flower set up",
      "Entrance décor",
      "Mandap set-up",
      "Table décor",
      "Centerpieces",
      "Photobooth",
      "Sound setup",
      "Furniture",
      "Signages and stationery for the event",
      "On-site support staf",
    ],
  },
  {
    title: "Destination Wedding",
    slug: "destination-wedding",
    info: "Wedding Planners have arranged records of excellent wedding venues that would fit your budget and theme.",
    img1: "4",
    img2: "6",
    descriptionA:
      "A couple's wedding is an incredibly emotional occasion that is celebrated with various traditions and events in Indian culture. However, it can be overwhelming for couples to manage all of these events and achieve the perfect vision for their special day. ",
    descriptionB:
      "Choosing a proper wedding venue can be overwhelming, particularly if you plan to have your wedding at a location that you are not familiar with. However, with the help of destination wedding planners, you can make your dream wedding a reality. Wedding Planners have arranged records of excellent wedding venues that would fit your budget and theme. These planners understand that clients often have busy work schedules and prefer not to stress themselves out with wedding planning from afar. They specialize in managing all kinds of weddings, from small, intimate gatherings to large, extravagant celebrations. You can trust their team to take care of everything, from booking the perfect venue to managing vendors and executing your vision with passion and care.",
  },
  {
    title: "Birthday Party Planner",
    slug: "birthday-party-planner",
    info: "We offer a range of services to cater to all kinds of celebrations, from simple and elegant decorations to elaborate and themed setups.",
    img1: "16",
    img2: "8",
    descriptionA:
      "Wedding planners are a well-known and respected company in the event management industry, specializing in organizing birthday parties. We offer a range of services to cater to all kinds of celebrations, from simple and elegant decorations to elaborate and themed setups. We understand the importance of creating memorable moments for your loved ones, and that's why we offer our services for a variety of occasions, including birthdays, baby showers, naming ceremonies, and other children's parties. Let us help you make your celebrations truly special and unforgettable. Skilled party planners are capable of designing a stunning and remarkable space that complements your chosen theme. Whether you desire floral arrangements and decorations, coordinated color schemes, or a beautifully lit party, they have everything covered to make your dream birthday party a reality. This will undoubtedly evoke strong emotions and leave a lasting impression on you and your guests.",
    descriptionB:
      "Wedding cake and catering Food is one thing that each of your wedding guests will remember even after years, and therefore it's essential to book a  talented caterer that will work together with your requests and requirements. Wedding planners in Raipur will help you book the best one under your budget. More than a tradition, having a wedding cake on your big day has become a trend. With numerous beautiful designs and delicious flavors available, you'll find a tremendous bridecake with the assistance of your chosen wedding planners.",
  },
  {
    title: "Photography, Videography ",
    slug: "photographers-videography",
    info: "With the help of professional photographers, you can capture breathtaking moments from your wedding that will remain close to your heart forever",
    img1: "9",
    img2: "10",
    descriptionA:
      "Indian weddings are known for their rich traditions and numerous events that make up the celebration. From the engagement to the pre-wedding shoot to the post-wedding reception, there are several photography services available to capture every moment. You can either choose one photographer to cover the entire wedding or opt for different photographers for each occasion. These photographers are extremely talented and can add a personal touch to your pictures by incorporating unique and creative ideas. You can share your ideas and preferences with them within your budget. With the help of professional photographers, you can capture breathtaking moments from your wedding that will remain close to your heart forever.",
    descriptionB:
      "Wedding Planners have an inventory of associate photographers who will capture each moment of your wedding including trending ones like: ",
    list: [
      "Traditional photography",
      "Candid photography",
      "Cinematographic",
      "Drone shoots",
      "Live Screening",
      "Photobooths",
    ],
  },
  {
    title: "Pre Wedding ",
    slug: "pre-wedding",
    info: "Pre-wedding shoot has to be really special with glittery ideas and B&W shoots or candid poses, you just can't get enough of it!",
    img1: "17",
    img2: "1",
    descriptionA:
      "Indian weddings are known for their rich traditions and numerous events that make up the celebration. From the engagement to the pre-wedding shoot to the post-wedding reception, there are several photography services available to capture every moment. You can either choose one photographer to cover the entire wedding or opt for different photographers for each occasion. These photographers are extremely talented and can add a personal touch to your pictures by incorporating unique and creative ideas. You can share your ideas and preferences with them within your budget. With the help of professional photographers, you can capture breathtaking moments from your wedding that will remain close to your heart forever.",
    descriptionB:
      "Wedding Planners have an inventory of associate photographers who will capture each moment of your wedding including trending ones like: ",
    list: [
      "Traditional photography",
      "Candid photography",
      "Cinematographic",
      "Drone shoots",
      "Live Screening",
      "Photobooths",
    ],
  },
  {
    title: "Event Planner",
    slug: "event-planner",
    info: "These best event planners can assist you in discovering inventive and creative ways that coordinate with the theme of your event.",
    img1: "12",
    img2: "13",
    descriptionA:
      "Wedding planners believe in innovative events because they want it to be your special event and not an event looking like someone else. For them, every event is an opportunity where their team can show you their best work. Wedding planners systematically do everything. Skilled event planners are capable of designing a stunning and remarkable space that complements your chosen theme and the occasion. Whether you desire decorations, photographers, caterers, hospitality and guest services, they have everything covered to make your event a memorable reality. This will undoubtedly evoke strong emotions and leave a lasting impression on you and your guests.",
    descriptionB:
      "These best event planners can assist you in discovering inventive and creative ways that coordinate with the theme of your event. ",
  },
  {
    title: "Flower Decor",
    slug: "flower-decor",
    info: "Wedding Planners has got you covered whether you need professional flower arrangements for halls, engagement ceremonies, mandaps, or parties. ",
    img1: "14",
    img2: "15",
    descriptionA:
      "When it comes to creating stunning floral arrangements for weddings, parties, banquets, corporate events, and other special occasions, Wedding Planners is the go-to choice. They specialize in creating one-of-a-kind designs that are both beautiful and unique. Whether you need professional flower arrangements or decoration for convention halls, engagement ceremonies, mandaps, or parties, Wedding Planners has got you covered.",
    descriptionB:
      "They have a team of highly skilled and creative professionals who are passionate about making your special day unforgettable and they specialize in managing all kinds of floral decorations for, from small, intimate gatherings to large, extravagant celebrations. You can trust their team to take care of everything For the most emotional and breathtaking wedding decoration, look no further than Wedding Planners.",
  },
  {
    title: "Wedding Package",
    slug: "wedding-package",
    info: "Get the best quote from Wedding Planners for a complete wedding package and book your date!",
    img1: "12",
    img2: "13",
    descriptionA:
      "Wedding planners believe in innovative events because they want it to be your special event and not an event looking like someone else. For them, every event is an opportunity where their team can show you their best work. Wedding planners systematically do everything. Skilled event planners are capable of designing a stunning and remarkable space that complements your chosen theme and the occasion. Whether you desire decorations, photographers, caterers, hospitality and guest services, they have everything covered to make your event a memorable reality. This will undoubtedly evoke strong emotions and leave a lasting impression on you and your guests.",
    descriptionB:
      "These best event planners can assist you in discovering inventive and creative ways that coordinate with the theme of your event. ",
  },
];
